server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: ms-stock
          uri: lb://MS-STOCK
          predicates:
            - Path=/stock/**

        - id: ms-pedidos
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/pedidos/**

        - id: ms-notificaciones
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/notificaciones/**

        - id: ms-pagos
          uri: lb://MS-PAGOS
          predicates:
            - Path=/pagos/**

        - id: ms-catalogo
          uri: lb://MS-CATALOGO
          predicates:
            - Path=/catalogo/**

        - id: ms-envios
          uri: lb://MS-ENVIOS
          predicates:
            - Path=/envios/**

        - id: ms-resenas
          uri: lb://MS-RESENAS
          predicates:
            - Path=/resenas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka